### ISSUE TITLE
config.properties文件没有效果

### ISSUE THREAD

**Issue by letsgo008** [wongoo/aliwepaystat#1]
config.properties里面变化参数后，没有效果，还是默认的设置。

**Comment by wongoo** [comment]
@letsgo008 修改参数后重新执行，会产生新的html，尝试刷新一下，看能否看到新的结果。

**Comment by letsgo008** [comment]
我试了在config.go里直接改，编译后生效的。但是直接改config.properties文件没有效果。
![image](https://user-images.githubusercontent.com/3468407/93879535-6ee39700-fd0e-11ea-8ca8-4e94e9c8c2c4.png)

**Comment by wongoo** [comment]
配置文件默认会读取和二进制文件同一个目录下的config.properties文件，参考 https://github.com/wongoo/aliwepaystat/blob/master/cmd/aliwepaystat/aliwepaystat.go ， 也可以指定配置文件完整路径, 如 ` aliwepaystat -c /User/letsgo008/config.properties`

**Comment by letsgo008** [comment]
@wongoo 这次加参数可以了，谢谢啊

**Comment by wongoo** [comment]
有问题随时提，有想要改进的问题也可以提。
